import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MqttProvider } from "@/contexts/mqtt";
import NotificationProvider from "@/contexts/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-950  text-slate-100`}>
        <header className="p-4 border-b border-slate-700">
          <h1 className="font-bold uppercase">Remote Controller</h1>
        </header>
        <MqttProvider>
          <NotificationProvider>
            {children}
          </NotificationProvider>
        </MqttProvider>
      </body>
    </html>
  );
}
